# Generated by Django 6.0.2 on 2026-02-23 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_ecoactionsubmission_delete_carbonemission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCarbonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transport_distance', models.FloatField(default=0)),
                ('transport_vehicle_type', models.CharField(blank=True, choices=[('car_petrol_large', 'Car (Petrol >1200 cc)'), ('car_petrol_small', 'Car (Petrol <1200 cc)'), ('bike_motorcycle', 'Bike (Motorcycle)'), ('bike_scooter', 'Bike (Scooter)'), ('bus_public', 'Bus (Public)'), ('train_rail', 'Train (Rail)')], max_length=50, null=True)),
                ('electricity_units', models.FloatField(default=0)),
                ('lpg_used', models.FloatField(default=0)),
                ('water_used', models.FloatField(default=0)),
                ('water_source', models.CharField(blank=True, choices=[('municipal', 'Municipal Supply'), ('borewell', 'Borewell Pump')], max_length=50, null=True)),
                ('waste_weight', models.FloatField(default=0)),
                ('waste_type_method', models.CharField(blank=True, choices=[('organic_landfill', 'Organic Waste (Landfill)'), ('organic_composted', 'Organic Waste (Composted)'), ('paper', 'Paper Waste')], max_length=50, null=True)),
                ('total_co2', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
