# Generated by Django 5.2.11 on 2026-02-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_dailycarbonreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycarbonreport',
            name='energy_co2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailycarbonreport',
            name='transport_co2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailycarbonreport',
            name='waste_co2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailycarbonreport',
            name='water_co2',
            field=models.FloatField(default=0),
        ),
    ]
