# Generated by Django 5.2.11 on 2026-02-26 00:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_dailycarbonreport_energy_co2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailycarbonreport',
            unique_together={('user', 'date')},
        ),
    ]
