# Generated by Django 5.2.11 on 2026-03-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_dailycarbonreport_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycarbonreport',
            name='transport_vehicle_type',
            field=models.CharField(blank=True, choices=[('car_petrol_large', 'Car (Petrol >1202 cc)'), ('car_petrol_small', 'Car (Petrol <1202 cc)'), ('bike_motorcycle', 'Bike (Motorcycle)'), ('bike_scooter', 'Bike (Scooter)'), ('bus_public', 'Bus (Public)'), ('train_rail', 'Train (Rail)')], max_length=50, null=True),
        ),
    ]
