# Generated by Django 6.0.1 on 2026-02-22 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_credit', models.FloatField()),
                ('available_credits', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketplacetransaction',
            name='buyer',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_used', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.rewardproject')),
            ],
        ),
        migrations.DeleteModel(
            name='CarbonCredit',
        ),
        migrations.DeleteModel(
            name='MarketplaceTransaction',
        ),
    ]
