# Generated by Django 6.0.1 on 2026-02-22 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rewardproject_remove_marketplacetransaction_buyer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='credits_used',
            new_name='credits_bought',
        ),
        migrations.RenameField(
            model_name='rewardproject',
            old_name='is_verified',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='rewardproject',
            old_name='name',
            new_name='organization_name',
        ),
        migrations.RemoveField(
            model_name='rewardproject',
            name='available_credits',
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardproject',
            name='credits_available',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
