# Generated by Django 6.0.2 on 2026-02-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_credits_used_purchase_credits_bought_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardproject',
            options={'verbose_name': 'Credit Market', 'verbose_name_plural': 'Credit Market'},
        ),
    ]
